apiVersion: v1
kind: Pod
metadata:
  namespace: microservices-demo
  name: redis
  labels:
    app: redis
spec:
  containers:
    - name: redis
      image: redis
      args: ["redis-server", "--appendonly", "yes"]
      ports:
        - containerPort: 6379
      volumeMounts:
        - mountPath: "/data"
          name: redis-storage
  volumes:
    - name: redis-storage
      persistentVolumeClaim:
        claimName: redis-pvc