apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: microservices-demo
  name: redis-pvc
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi