apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: microservices-demo
  name: cartservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
        - name: cartservice
          image: us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice:v0.10.3
          ports:
            - containerPort: 7070