apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: microservices-demo
  name: shippingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
        - name: shippingservice
          image: us-central1-docker.pkg.dev/google-samples/microservices-demo/shippingservice:v0.10.3
          ports:
            - containerPort: 50051