apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: microservices-demo
  name: checkoutservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
        - name: checkoutservice
          image: us-central1-docker.pkg.dev/google-samples/microservices-demo/checkoutservice:v0.10.3
          ports:
            - containerPort: 5050
          env:
            - name: SHIPPING_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: microservices-demo-config
                  key: SHIPPING_SERVICE_ADDR
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: microservices-demo-config
                  key: PRODUCT_CATALOG_SERVICE_ADDR
            - name: CART_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: microservices-demo-config
                  key: CART_SERVICE_ADDR
            - name: CURRENCY_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: microservices-demo-config
                  key: CURRENCY_SERVICE_ADDR
            - name: EMAIL_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: microservices-demo-config
                  key: EMAIL_SERVICE_ADDR
            - name: PAYMENT_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: microservices-demo-config
                  key: PAYMENT_SERVICE_ADDR