apiVersion: v1
kind: ConfigMap
metadata:
  namespace: microservices-demo
  name: microservices-demo-config
data:
  DISABLE_PROFILER: "1"
  CURRENCY_PORT: "7000"
  PAYMENT_PORT: "50051"
  PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
  SHIPPING_SERVICE_ADDR: "shippingservice:50051"
  CART_SERVICE_ADDR: "cartservice:7070"
  CURRENCY_SERVICE_ADDR: "currencyservice:7000"
  EMAIL_SERVICE_ADDR: "emailservice:8080"
  PAYMENT_SERVICE_ADDR: "paymentservice:50051"
  RECOMMENDATION_SERVICE_ADDR: "recommendationservice:8080"
  CHECKOUT_SERVICE_ADDR: "checkoutservice:5050"
  AD_SERVICE_ADDR: "adservice:9555"
  SHOPPING_ASSISTANT_SERVICE_ADDR: "shoppingassistantservice:80"